import Head from 'next/head'

import axios from 'axios';
import { useEffect } from 'react';


export default function Home() {

  useEffect(() => {
    axios.get('https://django-nubank-b1e0ca266a24.herokuapp.com')
    .then((res) => {
      console.log(res.data);
    })
    .catch((err) => {
      console.log(err);
    })
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    </>
  )
}
